export const allProducts = [
  {
    id: 1,
    img: "./assets/images/products/product-1.jpg",
    title: " مغازه‌ی خودکشی ",
    price: 45_000,
    count: 1,
  },
  {
    id: 2,
    img: "./assets/images/products/product-2.jpg",
    title: " حکایت دولت و فرزانگی ",
    price: 58_000,
    count: 1,
  },
  {
    id: 3,
    img: "./assets/images/products/product-3.jpg",
    title: " هنر شفاف اندیشیدن",
    price: 89_000,
    count: 1,
  },
  {
    id: 4,
    img: "./assets/images/products/product-4.jpg",
    title: "خانه درختی 104 طبقه",
    price: 105_000,
    count: 1,
  },
  {
    id: 5,
    img: "./assets/images/products/product-5.jpg",
    title: " شازده کوچولو ",
    price: 65_000,
    count: 1,
  },
  {
    id: 6,
    img: "./assets/images/products/product-6.jpg",
    title: "جزء از کل",
    price: 58_000,
    count: 1,
  },
  {
    id: 7,
    img: "./assets/images/products/product-7.jpg",
    title: " من، پیش از تو ",
    price: 45_000,
    count: 1,
  },
  {
    id: 8,
    img: "./assets/images/products/product-8.jpg",
    title: "  آداب بی‌قراری ",
    price: 77_000,
    count: 1,
  },
];
